[
    {
            "hashKey": -857787,
            "geoJson": "{\"coordinates\":[34.063514,-84.724564],\"type\":\"Point\"}",
            "geohash": -8577871795095664463,
            "recordId": "358013",
            "address": "4395 Acworth Dallas Rd",
            "address2": "Suite 100",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Acworth",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.063514",
            "lc": "33454002",
            "lng": "-84.724564",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-675-3774",
            "postal": "30101",
            "sat_hours": "05:00-22:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": "Y",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 1.753712564104832,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": "1028335",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857788,
            "geoJson": "{\"coordinates\":[34.032908,-84.671541],\"type\":\"Point\"}",
            "geohash": -8577880240031496125,
            "recordId": "349086",
            "address": "3139 Cobb Pkwy NW",
            "address2": "Ste 100",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "04:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.032908",
            "lc": "33454002",
            "lng": "-84.671541",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "04:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-974-9717",
            "postal": "30152",
            "sat_hours": "04:00-22:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "05:00-22:00",
            "thu_hours": "04:00-22:00",
            "tue_hours": "04:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "04:00-22:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "05:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 2.0285893509296526,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501305773",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "05:00-21:00",
            "mon_dining_hours": "04:00-21:00",
            "tue_dining_hours": "04:00-21:00",
            "wed_dining_hours": "04:00-21:00",
            "thu_dining_hours": "04:00-21:00",
            "fri_dining_hours": "04:00-21:00",
            "sat_dining_hours": "04:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857788,
            "geoJson": "{\"coordinates\":[34.012615,-84.754108],\"type\":\"Point\"}",
            "geohash": -8577888098802053601,
            "recordId": "355013",
            "address": "8879 Dallas Acworth Hwy",
            "address2": "Suite 200",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Dallas",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Paulding",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-975-0682",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.012615",
            "lc": "33454002",
            "lng": "-84.754108",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-975-0682",
            "postal": "30132",
            "sat_hours": "05:00-21:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 3.6222682368602808,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501307699",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857787,
            "geoJson": "{\"coordinates\":[34.083818,-84.655414],\"type\":\"Point\"}",
            "geohash": -8577878437058176445,
            "recordId": "353268",
            "address": "130 Northpoint Pkwy",
            "address2": "Suite 100",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Acworth",
            "close_reason_cd": " ",
            "co_brander_cd": "BP",
            "combostore": "N",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.083818",
            "lc": "33454002",
            "lng": "-84.655414",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-503-8388",
            "postal": "30102",
            "sat_hours": "05:00-21:00",
            "sitetype": "GC",
            "state": "GA",
            "sun_hours": "06:00-20:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 3.878592959877103,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501307256",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "06:00-20:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857787,
            "geoJson": "{\"coordinates\":[34.047725,-84.61018],\"type\":\"Point\"}",
            "geohash": -8577879423061727505,
            "recordId": "349401",
            "address": "4100 Jiles Rd NW",
            "address2": "Ste 100",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.047725",
            "lc": "33454002",
            "lng": "-84.61018",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-275-2187",
            "postal": "30144",
            "sat_hours": "05:00-22:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 5.374235681779346,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501305878",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857787,
            "geoJson": "{\"coordinates\":[34.013858,-84.614796],\"type\":\"Point\"}",
            "geohash": -8577879651498711531,
            "recordId": "356296",
            "address": "2462 Kennesaw Due West Rd NW",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.013858",
            "lc": "33454002",
            "lng": "-84.614796",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-996-4150",
            "postal": "30152",
            "sat_hours": "05:00-22:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 5.532612210260001,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "1025211",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.061162,-84.593211],\"type\":\"Point\"}",
            "geohash": -8577832717923360909,
            "recordId": "353605",
            "address": "4443 Wade Green Rd NW",
            "address2": "Suite 116",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.061162",
            "lc": "33454002",
            "lng": "-84.593211",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-218-0909",
            "postal": "30144",
            "sat_hours": "05:00-22:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 6.442141647808118,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501307356",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "06:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.99486,-84.59122],\"type\":\"Point\"}",
            "geohash": -8577926315579281733,
            "recordId": "345878",
            "address": "1610 Ridenour Blvd NW",
            "address2": "Suite 101",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-514-9096",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.99486",
            "lc": "33454002",
            "lng": "-84.59122",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-514-9095",
            "postal": "30152",
            "sat_hours": "05:00-21:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-20:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 7.316361957944217,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501305161",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.035906,-84.572133],\"type\":\"Point\"}",
            "geohash": -8577832460836532915,
            "recordId": "336381",
            "address": "741 Townpark Ln NW",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-420-2723",
            "fri_hours": "05:00-23:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.035906",
            "lc": "33454002",
            "lng": "-84.572133",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-23:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-355-5518",
            "postal": "30144",
            "sat_hours": "05:00-23:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-23:00",
            "thu_hours": "05:00-23:00",
            "tue_hours": "05:00-23:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-23:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-22:00",
            "tue_cs_hours": "05:00-22:00",
            "wed_cs_hours": "05:00-22:00",
            "thu_cs_hours": "05:00-22:00",
            "fri_cs_hours": "05:00-22:00",
            "sat_cs_hours": "05:00-22:00",
            "sun_cs_hours": "06:00-22:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 7.572137330382814,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501302699",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-22:00",
            "mon_dining_hours": "05:00-22:00",
            "tue_dining_hours": "05:00-22:00",
            "wed_dining_hours": "05:00-22:00",
            "thu_dining_hours": "05:00-22:00",
            "fri_dining_hours": "05:00-22:00",
            "sat_dining_hours": "05:00-22:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857788,
            "geoJson": "{\"coordinates\":[33.945772,-84.6232],\"type\":\"Point\"}",
            "geohash": -8577881875453605449,
            "recordId": "310095",
            "address": "2475 Dallas Hwy SW",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-792-0492",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.945772",
            "lc": "33454002",
            "lng": "-84.6232",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-792-6677",
            "postal": "30064",
            "sat_hours": "06:00-21:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-20:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 8.250527776061256,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501301744",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "07:00-19:00",
            "mon_dining_hours": "06:00-20:00",
            "tue_dining_hours": "06:00-20:00",
            "wed_dining_hours": "06:00-20:00",
            "thu_dining_hours": "06:00-20:00",
            "fri_dining_hours": "06:00-20:00",
            "sat_dining_hours": "07:00-20:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.056117,-84.557548],\"type\":\"Point\"}",
            "geohash": -8577832161913973085,
            "recordId": "310096",
            "address": "4311 Bells Ferry Rd",
            "address2": "Ste A",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Kennesaw",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.056117",
            "lc": "33454002",
            "lng": "-84.557548",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-926-3933",
            "postal": "30144",
            "sat_hours": "24HOURS",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 8.418798954466483,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": "501301745",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.951671,-84.57512],\"type\":\"Point\"}",
            "geohash": -8577925888980901457,
            "recordId": "356161",
            "address": "751 Whitlock Ave SW",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-23:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.951671",
            "lc": "33454002",
            "lng": "-84.57512",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-575-4107",
            "postal": "30064",
            "sat_hours": "05:00-23:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "05:00-22:00",
            "tue_cs_hours": "05:00-22:00",
            "wed_cs_hours": "05:00-22:00",
            "thu_cs_hours": "05:00-22:00",
            "fri_cs_hours": "05:00-22:00",
            "sat_cs_hours": "05:00-22:00",
            "sun_cs_hours": "06:00-22:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 9.784100635138868,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "1016968",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-22:00",
            "mon_dining_hours": "05:00-22:00",
            "tue_dining_hours": "05:00-22:00",
            "wed_dining_hours": "05:00-22:00",
            "thu_dining_hours": "05:00-22:00",
            "fri_dining_hours": "05:00-22:00",
            "sat_dining_hours": "05:00-22:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857788,
            "geoJson": "{\"coordinates\":[33.90292,-84.67319],\"type\":\"Point\"}",
            "geohash": -8577883350854877631,
            "recordId": "355732",
            "address": "4100 Macland Rd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Powder Springs",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.90292",
            "lc": "33454002",
            "lng": "-84.67319",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-540-8155",
            "postal": "30127",
            "sat_hours": "05:00-22:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "05:00-21:00",
            "tue_cs_hours": "05:00-21:00",
            "wed_cs_hours": "05:00-21:00",
            "thu_cs_hours": "05:00-21:00",
            "fri_cs_hours": "05:00-21:00",
            "sat_cs_hours": "05:00-21:00",
            "sun_cs_hours": "06:00-21:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 9.947960695560448,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "1019016",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://gadonuts.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[34.021243,-84.528892],\"type\":\"Point\"}",
            "geohash": -8577927171665179017,
            "recordId": "308655",
            "address": "2885 Canton Hwy",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "678-560-8731",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.021243",
            "lc": "33454002",
            "lng": "-84.528892",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-422-3375",
            "postal": "30066",
            "sat_hours": "05:00-22:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-22:00",
            "tue_cs_hours": "05:00-22:00",
            "wed_cs_hours": "05:00-22:00",
            "thu_cs_hours": "05:00-22:00",
            "fri_cs_hours": "05:00-22:00",
            "sat_cs_hours": "05:00-22:00",
            "sun_cs_hours": "06:00-22:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 10.153209714580933,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501301666",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-22:00",
            "mon_dining_hours": "05:00-22:00",
            "tue_dining_hours": "05:00-22:00",
            "wed_dining_hours": "05:00-22:00",
            "thu_dining_hours": "05:00-22:00",
            "fri_dining_hours": "05:00-22:00",
            "sat_dining_hours": "05:00-22:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.086839,-84.527956],\"type\":\"Point\"}",
            "geohash": -8577831692084790897,
            "recordId": "336992",
            "address": "9755 Hwy 92",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Woodstock",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.086839",
            "lc": "33454002",
            "lng": "-84.527956",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-926-7770",
            "postal": "30188",
            "sat_hours": "24HOURS",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 10.485679842147798,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501302874",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.101845,-84.532994],\"type\":\"Point\"}",
            "geohash": -8577831247348775879,
            "recordId": "336181",
            "address": "875 Towne Lake Parkway",
            "address2": "Ste D",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Woodstock",
            "close_reason_cd": " ",
            "co_brander_cd": "BDT",
            "combostore": "Y",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.101845",
            "lc": "33454002",
            "lng": "-84.532994",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-928-2582",
            "postal": "30188",
            "sat_hours": "24HOURS",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 10.550798063435055,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501302672",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857786,
            "geoJson": "{\"coordinates\":[34.187412,-84.787175],\"type\":\"Point\"}",
            "geohash": -8577862432729073485,
            "recordId": "350736",
            "address": "101 Gentilly Blvd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Cartersville",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Bartow",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.187412",
            "lc": "33454002",
            "lng": "-84.787175",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-382-0382",
            "postal": "30120",
            "sat_hours": "05:00-21:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "06:00-18:00",
            "tue_cs_hours": "06:00-18:00",
            "wed_cs_hours": "06:00-18:00",
            "thu_cs_hours": "06:00-18:00",
            "fri_cs_hours": "06:00-18:00",
            "sat_cs_hours": "06:00-18:00",
            "sun_cs_hours": "06:00-18:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 10.945072855707267,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501306365",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857788,
            "geoJson": "{\"coordinates\":[33.890705,-84.754086],\"type\":\"Point\"}",
            "geohash": -8577885505499993125,
            "recordId": "331517",
            "address": "4470 Jimmy Lee Smith Pkwy",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Hiram",
            "close_reason_cd": " ",
            "co_brander_cd": "BRD",
            "combostore": "N",
            "country": "US",
            "county": "Paulding",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.890705",
            "lc": "33454002",
            "lng": "-84.754086",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "678-567-0630",
            "postal": "30141",
            "sat_hours": "05:00-21:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "06:00-20:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 11.013522217378764,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501302205",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "08:00-17:00",
            "mon_dining_hours": "07:00-17:00",
            "tue_dining_hours": "07:00-17:00",
            "wed_dining_hours": "07:00-17:00",
            "thu_dining_hours": "07:00-17:00",
            "fri_dining_hours": "07:00-17:00",
            "sat_dining_hours": "08:00-17:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.926412,-84.571239],\"type\":\"Point\"}",
            "geohash": -8577925283926439045,
            "recordId": "359775",
            "address": "1101 Powder Springs Street",
            "address2": " ",
            "adv_ord": "N",
            "almond": "N",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "N",
            "dunkincardenabled": "N",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "N",
            "kosher": "N",
            "lat": "33.926412",
            "lc": "33454002",
            "lng": "-84.571239",
            "loyalty": "N",
            "mobile": "N",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "7",
            "phonenumber": "--",
            "postal": "30064",
            "sat_hours": "24HOURS",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "N",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "N",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": "Y",
            "dt_auto_fire": " ",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 11.159242468009102,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": " ",
            "pos_type": "Non-Approved",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": " ",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": null,
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": null
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.942728,-84.533515],\"type\":\"Point\"}",
            "geohash": -8577925004595148787,
            "recordId": "307688",
            "address": "670 S Marietta Pkwy",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-422-1263",
            "fri_hours": "05:00-23:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.942728",
            "lc": "33454002",
            "lng": "-84.533515",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-423-5947",
            "postal": "30060",
            "sat_hours": "06:00-23:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "06:00-18:00",
            "tue_cs_hours": "06:00-18:00",
            "wed_cs_hours": "06:00-18:00",
            "thu_cs_hours": "06:00-18:00",
            "fri_cs_hours": "06:00-18:00",
            "sat_cs_hours": "06:00-18:00",
            "sun_cs_hours": "06:00-18:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 12.037202293379842,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501301510",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "05:00-23:00",
            "mon_dining_hours": "05:00-23:00",
            "tue_dining_hours": "05:00-23:00",
            "wed_dining_hours": "05:00-23:00",
            "thu_dining_hours": "05:00-23:00",
            "fri_dining_hours": "05:00-23:00",
            "sat_dining_hours": "05:00-23:00",
            "high_vol_brewer": "N",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[34.016724,-84.492849],\"type\":\"Point\"}",
            "geohash": -8577928771216184207,
            "recordId": "304785",
            "address": "2765 Sandy Plains Rd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "678-560-8731",
            "fri_hours": "05:00-23:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.016724",
            "lc": "33454002",
            "lng": "-84.492849",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-977-2722",
            "postal": "30066",
            "sat_hours": "05:00-23:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "Y",
            "curbside": "Y",
            "mon_cs_hours": "05:00-22:00",
            "tue_cs_hours": "05:00-22:00",
            "wed_cs_hours": "05:00-22:00",
            "thu_cs_hours": "05:00-22:00",
            "fri_cs_hours": "05:00-22:00",
            "sat_cs_hours": "05:00-22:00",
            "sun_cs_hours": "06:00-22:00",
            "next_gen_store": "Y",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 12.239839214149073,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "Y",
            "pos_cmc_id": " ",
            "pos_type": "Simphony",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://coffeecafejobs.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-22:00",
            "mon_dining_hours": "05:00-22:00",
            "tue_dining_hours": "05:00-22:00",
            "wed_dining_hours": "05:00-22:00",
            "thu_dining_hours": "05:00-22:00",
            "fri_dining_hours": "05:00-22:00",
            "sat_dining_hours": "05:00-22:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.172511,-84.548997],\"type\":\"Point\"}",
            "geohash": -8577834586363403301,
            "recordId": "356627",
            "address": "180 Vince Merolla Dr",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Canton",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.172511",
            "lc": "33454002",
            "lng": "-84.548997",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-224-6168",
            "postal": "30114",
            "sat_hours": "24HOURS",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": "Y",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 12.51160983380014,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": "1024204",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": " ",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857783,
            "geoJson": "{\"coordinates\":[34.041435,-84.481427],\"type\":\"Point\"}",
            "geohash": -8577830239883093239,
            "recordId": "353902",
            "address": "2378 Shallowford Rd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.041435",
            "lc": "33454002",
            "lng": "-84.481427",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-591-9906",
            "postal": "30066",
            "sat_hours": "05:00-21:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "05:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "06:00-18:00",
            "tue_cs_hours": "06:00-18:00",
            "wed_cs_hours": "06:00-18:00",
            "thu_cs_hours": "06:00-18:00",
            "fri_cs_hours": "06:00-18:00",
            "sat_cs_hours": "06:00-18:00",
            "sun_cs_hours": "06:00-18:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 12.740554774441664,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501307738",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "05:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.97476,-84.479],\"type\":\"Point\"}",
            "geohash": -8577929768682902737,
            "recordId": "348449",
            "address": "980 E Piedmont Rd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-971-8365",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.97476",
            "lc": "33454002",
            "lng": "-84.479",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-971-8360",
            "postal": "30062",
            "sat_hours": "05:00-21:00",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "05:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "06:00-18:00",
            "tue_cs_hours": "06:00-18:00",
            "wed_cs_hours": "06:00-18:00",
            "thu_cs_hours": "06:00-18:00",
            "fri_cs_hours": "06:00-18:00",
            "sat_cs_hours": "06:00-18:00",
            "sun_cs_hours": "06:00-18:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 13.757661519742557,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501305624",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "05:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857782,
            "geoJson": "{\"coordinates\":[34.086986,-84.468485],\"type\":\"Point\"}",
            "geohash": -8577829267266002821,
            "recordId": "358663",
            "address": "600 Claremore Professional Way",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "N",
            "beverageonly": "N",
            "city": "Woodstock",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.086986",
            "lc": "33454002",
            "lng": "-84.468485",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-928-2913",
            "postal": "30188",
            "sat_hours": "24HOURS",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": "Y",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 13.788878531237152,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": " ",
            "pos_type": "Simphony",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": " ",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857782,
            "geoJson": "{\"coordinates\":[34.19829,-84.5085],\"type\":\"Point\"}",
            "geohash": -8577827478008328807,
            "recordId": "350554",
            "address": "3640 Marietta Hwy",
            "address2": "Suite A",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Canton",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cherokee",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "24HOURS",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.19829",
            "lc": "33454002",
            "lng": "-84.5085",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "24HOURS",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-345-4433",
            "postal": "30114",
            "sat_hours": "24HOURS",
            "sitetype": "EC",
            "state": "GA",
            "sun_hours": "24HOURS",
            "thu_hours": "24HOURS",
            "tue_hours": "24HOURS",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "24HOURS",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 15.412082363701781,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": "N",
            "pos_cmc_id": "501306292",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "24HOURS",
            "mon_dining_hours": "24HOURS",
            "tue_dining_hours": "24HOURS",
            "wed_dining_hours": "24HOURS",
            "thu_dining_hours": "24HOURS",
            "fri_dining_hours": "24HOURS",
            "sat_dining_hours": "24HOURS",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857792,
            "geoJson": "{\"coordinates\":[33.873661,-84.531011],\"type\":\"Point\"}",
            "geohash": -8577924315755114811,
            "recordId": "302925",
            "address": "3300 S. Cobb Dr",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Smyrna",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-436-2711",
            "fri_hours": "05:00-22:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.873661",
            "lc": "33454002",
            "lng": "-84.531011",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-22:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-436-6350",
            "postal": "30080",
            "sat_hours": "05:00-22:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-22:00",
            "thu_hours": "05:00-22:00",
            "tue_hours": "05:00-22:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-22:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 15.418081815170092,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501300906",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://www.itsnevertoolatte.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-19:00",
            "mon_dining_hours": "05:00-19:00",
            "tue_dining_hours": "05:00-19:00",
            "wed_dining_hours": "05:00-19:00",
            "thu_dining_hours": "05:00-19:00",
            "fri_dining_hours": "05:00-19:00",
            "sat_dining_hours": "05:00-19:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857793,
            "geoJson": "{\"coordinates\":[33.903162,-84.484697],\"type\":\"Point\"}",
            "geohash": -8577931194618926683,
            "recordId": "351894",
            "address": "2340 Windy Hill Rd SE",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Marietta",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.903162",
            "lc": "33454002",
            "lng": "-84.484697",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-859-2000",
            "postal": "30067",
            "sat_hours": "05:00-21:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 15.915797328599186,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501306803",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "06:00-19:00",
            "mon_dining_hours": "05:00-19:00",
            "tue_dining_hours": "05:00-19:00",
            "wed_dining_hours": "05:00-19:00",
            "thu_dining_hours": "05:00-19:00",
            "fri_dining_hours": "05:00-19:00",
            "sat_dining_hours": "05:00-19:00",
            "high_vol_brewer": "N",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857782,
            "geoJson": "{\"coordinates\":[34.062667,-84.422265],\"type\":\"Point\"}",
            "geohash": -8577823961738560313,
            "recordId": "353213",
            "address": "4691 Woodstock Rd",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Roswell",
            "close_reason_cd": " ",
            "co_brander_cd": " ",
            "combostore": "N",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "--",
            "fri_hours": "05:00-21:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "34.062667",
            "lc": "33454002",
            "lng": "-84.422265",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-21:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-518-3392",
            "postal": "30075",
            "sat_hours": "05:00-21:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "05:00-21:00",
            "thu_hours": "05:00-21:00",
            "tue_hours": "05:00-21:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-21:00",
            "wireless": "N",
            "curbside": "Y",
            "mon_cs_hours": "06:00-18:00",
            "tue_cs_hours": "06:00-18:00",
            "wed_cs_hours": "06:00-18:00",
            "thu_cs_hours": "06:00-18:00",
            "fri_cs_hours": "06:00-18:00",
            "sat_cs_hours": "06:00-18:00",
            "sun_cs_hours": "06:00-18:00",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 16.170144685734638,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501307239",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": " ",
            "apply_online": "N",
            "sun_dining_hours": "05:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }, {
            "hashKey": -857793,
            "geoJson": "{\"coordinates\":[33.888226,-84.473489],\"type\":\"Point\"}",
            "geohash": -8577931974745108617,
            "recordId": "302140",
            "address": "2651 Cobb Pky NW",
            "address2": " ",
            "adv_ord": "Y",
            "almond": "Y",
            "beverageonly": "N",
            "city": "Atlanta",
            "close_reason_cd": " ",
            "co_brander_cd": "STD",
            "combostore": "Y",
            "country": "US",
            "county": "Cobb",
            "dma_cd": "524",
            "drivein": "Y",
            "dunkincardenabled": "Y",
            "faxnumber": "770-569-2880",
            "fri_hours": "05:00-00:00",
            "k_cup": "Y",
            "kosher": "N",
            "lat": "33.888226",
            "lc": "33454002",
            "lng": "-84.473489",
            "loyalty": "Y",
            "mobile": "Y",
            "mon_hours": "05:00-23:00",
            "name": "Dunkin Donuts",
            "operation_status_cd": "2",
            "phonenumber": "770-952-2009",
            "postal": "30339",
            "sat_hours": "05:00-00:00",
            "sitetype": "FS",
            "state": "GA",
            "sun_hours": "06:00-23:00",
            "thu_hours": "05:00-23:00",
            "tue_hours": "05:00-23:00",
            "turbooven": "Y",
            "website": "https://www.dunkindonuts.com",
            "wed_hours": "05:00-23:00",
            "wireless": "Y",
            "curbside": "N",
            "mon_cs_hours": " ",
            "tue_cs_hours": " ",
            "wed_cs_hours": " ",
            "thu_cs_hours": " ",
            "fri_cs_hours": " ",
            "sat_cs_hours": " ",
            "sun_cs_hours": " ",
            "next_gen_store": " ",
            "dt_auto_fire": "Y",
            "catering_flag": "N",
            "mon_catering_hours": " ",
            "tue_catering_hours": " ",
            "wed_catering_hours": " ",
            "thu_catering_hours": " ",
            "fri_catering_hours": " ",
            "sat_catering_hours": " ",
            "sun_catering_hours": " ",
            "distance": 17.061951241441374,
            "tender_agnostic_enabled": "Y",
            "mobile_bypass_lane": " ",
            "pos_cmc_id": "501300684",
            "pos_type": "Radiant",
            "last_updated_datetime": "1591241470000",
            "dbi_fee_hr_link": "http://www.itsnevertoolatte.com/",
            "apply_online": "Y",
            "sun_dining_hours": "06:00-21:00",
            "mon_dining_hours": "05:00-21:00",
            "tue_dining_hours": "05:00-21:00",
            "wed_dining_hours": "05:00-21:00",
            "thu_dining_hours": "05:00-21:00",
            "fri_dining_hours": "05:00-21:00",
            "sat_dining_hours": "05:00-21:00",
            "high_vol_brewer": " ",
            "adl_add_info": null,
            "walkin_flag": "Y",
            "upsertTime": null,
            "otg_menu_opt": "RM"
        }
    ]